### ISSUE TITLE
What Llama/Vicuna API service does your code support?

### ISSUE THREAD

**Issue by wangruohui** [RICommunity/TAP#2]
Hello, 

I am trying to follow your wonderful work. I have noticed `class APIModel` implemented in your code. May I know which third-party service is this class exactly coded for and used in your experiments?

Thank you very much!

**Comment by paulkass** [comment]
Hi there, sorry for the late response, just saw this ticket.

So we have a custom API server that we use to call hosted models. This was designed to be a fairly generic class that accepts all model inference parameters as json in the body of the `POST` request to a certain API server. This was designed for our custom server, but feel free to modify this as you see fit for your case!
