### ISSUE TITLE
The performance of the reproduction is insufficient

### ISSUE THREAD

**Issue by byerose** [RICommunity/TAP#4]
I used vicuna-13b-1.5 as the attacker and gpt-4-1106-preview as the evaluator to attack vicuna-13b-1.5, with a success rate of the attack being only 70%.
the script:
```
CUDA_VISIBLE_DEVICES=6 nohup  python main_TAP.py \
    --attack-model 'vicuna' \
    --target-model 'vicuna' \
    --evaluator-model 'gpt-4-1106-preview' \
    --store-folder './store/vicuna2vicuna' \
    --branching-factor 4 \
    --depth 10 \
    --width 10 \
    > logs/vicuna2vicuna.log 2>&1 &
```

**Comment by LJSthu** [comment]
I set 'attack-model vicuna, target-model gpu-3.5-turbo, evaluator-model gpt-4-turbo', and found the success rate is only 30%. 

Also, after several iterations, the attack model will output None, and the iteration cannot proceed.
